apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::847460071840:role/eksctl-spring-cluster-nodegroup-wo-NodeInstanceRole-vtu5w1M4TGKG
      username: system:node:{{EC2PrivateDNSName}}

    - groups:
      - system:masters
      rolearn: arn:aws:iam::847460071840:role/CodePipelineStarterTemplate-PushToECR-CodeBuildRole-K47kR327FywT
      username: codebuild

  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::847460071840:user/Shenbagarajan
      username: admin