version: 0.2

env:
  variables:
    ImageName: spring-docker
    AccountId: 847460071840
    Region: ap-southeast-1
    ClusterName: spring-cluster

phases:

  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - aws ecr get-login-password --region $Region | docker login --username AWS --password-stdin $AccountId.dkr.ecr.$Region.amazonaws.com

      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 7)

      - echo IMAGE_TAG=$IMAGE_TAG

  build:
    commands:
      - mvn clean package -DskipTests

      - docker build --no-cache -t $ImageName:$IMAGE_TAG .

      - docker tag $ImageName:$IMAGE_TAG $AccountId.dkr.ecr.$Region.amazonaws.com/$ImageName:$IMAGE_TAG

      - docker tag $ImageName:$IMAGE_TAG $AccountId.dkr.ecr.$Region.amazonaws.com/$ImageName:latest

  post_build:
    commands:
      - docker push $AccountId.dkr.ecr.$Region.amazonaws.com/$ImageName:$IMAGE_TAG

      - docker push $AccountId.dkr.ecr.$Region.amazonaws.com/$ImageName:latest

      - aws eks update-kubeconfig --region $Region --name $ClusterName

      - kubectl set image deployment/springeksapp spring-docker=$AccountId.dkr.ecr.$Region.amazonaws.com/$ImageName:$IMAGE_TAG

      - kubectl rollout restart deployment/springeksapp

      - kubectl rollout status deployment/springeksapp