version: 0.2

env:
  variables:
    ImageName: springeksapp
    AccountId: 847460071840
    Region: ap-southeast-1

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $Region | docker login --username AWS --password-stdin $AccountId.dkr.ecr.$Region.amazonaws.com
  build:
    commands:
      - echo Build Spring Boot JAR...
      - mvn clean package -DskipTests
      - echo Build Docker image...
      - docker build -t $ImageName -f Dockerfile .
      - docker tag $ImageName:latest $AccountId.dkr.ecr.$Region.amazonaws.com/$ImageName:latest
  post_build:
    commands:
      - echo Push Docker image to ECR...
      - docker push $AccountId.dkr.ecr.$Region.amazonaws.com/$ImageName:latest
      - echo Update Kubernetes deployment...
      - aws eks update-kubeconfig --region $Region --name spring-cluster
      - kubectl set image deployment/$ImageName $ImageName=$AccountId.dkr.ecr.$Region.amazonaws.com/$ImageName:latest
